export type IncomeErrorCode =
	| "INCOME_INVALID_INPUT"
	| "INCOME_SOURCE_NOT_FOUND"
	| "INCOME_SOURCE_ARCHIVED"
	| "INCOME_SOURCE_CODE_CONFLICT"
	| "INCOME_LEDGER_ACCOUNT_INVALID"
	| "INCOME_DESTINATION_ACCOUNT_INVALID"
	| "INCOME_RECEIPT_NOT_FOUND"
	| "INCOME_RECEIPT_REVISION_CONFLICT"
	| "INCOME_RECEIPT_ALREADY_VOIDED"
	| "INCOME_RECEIPT_INVALID_STATE"
	| "INCOME_IDEMPOTENCY_CONFLICT"
	| "INCOME_REFERENCE_INVALID_STATE"
	| "INCOME_ENTITLEMENT_NOT_FOUND"
	| "INCOME_ENTITLEMENT_PERIOD_CONFLICT"
	| "INCOME_ENTITLEMENT_REVISION_CONFLICT"
	| "INCOME_ENTITLEMENT_ALREADY_VOIDED"
	| "INCOME_ENTITLEMENT_INVALID_STATE"
	| "INCOME_SETTLEMENT_NOT_FOUND"
	| "INCOME_SETTLEMENT_REVISION_CONFLICT"
	| "INCOME_SETTLEMENT_ALREADY_EXISTS"
	| "INCOME_SETTLEMENT_CONFLICT";

export class IncomeError extends Error {
	readonly code: IncomeErrorCode;

	constructor(code: IncomeErrorCode, message: string) {
		super(message);
		this.name = "IncomeError";
		this.code = code;
		Object.setPrototypeOf(this, new.target.prototype);
	}
}
